on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache the `chroot` environment
        id: cache-chroot
        uses: john-shaffer/cache@main
        with:
          path: /chroot-root
          key: ${{ runner.os }}-chroot-root-v0
      - name: Bootstrap the `chroot` environment
        if: steps.cache-chroot.outputs.cache-hit != 'true'
        run: |
          sudo rm -rf /chroot-root

          sudo apt-get update
          sudo apt-get -y install debootstrap

          sudo debootstrap --variant=minbase xenial /chroot-root
          sudo chroot /chroot-root /bin/bash -c "$(printf "\
          apt-get update &&\
          apt-get install -y \
            apt-transport-https ca-certificates \
            wget software-properties-common &&\
          \
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&\
          apt-add-repository \"deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\" &&\
          \
          apt-get update &&\
          apt-get install -y \
            clang-12 lld-12 \
            libgcc-5-dev lib32gcc-5-dev \
            libgcc-5-dev-arm64-cross libgcc-5-dev-armhf-cross \
            libc6-dev libc6-dev-i386 \
            libc6-dev-arm64-cross libc6-dev-armhf-cross \
          ")"
      - name: Cross-compile test C source code
        run: |
          cd ..
          sudo mv crossing /chroot-root
          sudo mkdir crossing
          cd crossing

          sudo chroot /chroot-root /bin/bash -c "$(printf "\
          cd crossing &&\
          \
          clang-12 crossing.c -o crossing-x86_64-linux -fuse-ld=lld -target x86_64-linux-gnu -O3 &&\
          clang-12 crossing.c -o crossing-x86_32-linux -fuse-ld=lld -target i386-linux-gnu -O3 &&\
          clang-12 crossing.c -o crossing-aarch64-linux -fuse-ld=lld -target aarch64-linux-gnu -O3 &&\
          clang-12 crossing.c -o crossing-armv7-linux -fuse-ld=lld -target armv7-linux-gnueabihf -O3 \
          ")"

          sudo mv /chroot-root/crossing/crossing-{x86_64,x86_32,aarch64,armv7}-linux .
          sudo rm -rf /chroot-root/crossing
      - name: Upload cross-compiled C program
        uses: actions/upload-artifact@v3
        with:
          name: crossing-linux
          path: |
            crossing-x86_64-linux
            crossing-x86_32-linux
            crossing-aarch64-linux
            crossing-armv7-linux
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cross-compile test C source code
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64

          x86_64-w64-mingw32-gcc crossing.c -o crossing-x86_64-windows.exe -O3
          i686-w64-mingw32-gcc crossing.c -o crossing-x86_32-windows.exe -O3
      - name: Upload cross-compiled C program
        uses: actions/upload-artifact@v3
        with:
          name: crossing-windows
          path: |
            crossing-x86_64-windows.exe
            crossing-x86_32-windows.exe
