on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install debootstrap

          sudo debootstrap --variant=minbase xenial crossing
          sudo chroot crossing /bin/bash -c "$(printf "\
          apt-get update \n\
          apt install \ \n\
            wget \ \n\
            software-properties-common \n\
          \n\
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \n\
          apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" \n\
          \n\
          apt-get update \n\
          apt-get install -y \ \n\
            clang-12 lld-12 \ \n\
            libgcc-5-dev lib32gcc-5-dev \ \n\
            libgcc-5-dev-arm64-cross libgcc-5-dev-armhf-cross \ \n\
            libc6-dev libc6-dev-i386 \ \n\
            libc6-dev-arm64-cross libc6-dev-armhf-cross \n\
          \n\
          ")"
