on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache the `chroot` environment
        id: cache-chroot
        uses: actions/cache@v3
        with:
          path: chroot-root
          key: ${{ runner.os }}-chroot-root-v0
      - name: Bootstrap the `chroot` environment
        if: steps.cache-chroot.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get -y install debootstrap

          sudo debootstrap --variant=minbase xenial chroot-root
          sudo chroot chroot-root /bin/bash -c "$(printf "\
          apt-get update &&\
          apt-get install -y \
            wget \
            software-properties-common &&\
          \
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&\
          apt-add-repository \"deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\" &&\
          \
          apt-get update &&\
          apt-get install -y \
            clang-12 lld-12 \
            libgcc-5-dev lib32gcc-5-dev \
            libgcc-5-dev-arm64-cross libgcc-5-dev-armhf-cross \
            libc6-dev libc6-dev-i386 \
            libc6-dev-arm64-cross libc6-dev-armhf-cross \
          \
          ")"
