on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache the `chroot` environment
        id: cache-chroot
        uses: john-shaffer/cache@main
        with:
          path: /chroot-root
          key: ${{ runner.os }}-chroot-root-v1
      - name: Bootstrap the `chroot` environment
        if: steps.cache-chroot.outputs.cache-hit != 'true'
        run: |
          sudo rm -rf /chroot-root

          sudo apt-get update
          sudo apt-get -y install debootstrap

          sudo debootstrap --variant=minbase xenial /chroot-root
          sudo chroot /chroot-root /bin/bash -c "$(printf "\
          apt-get update &&\
          apt-get install -y \
            apt-transport-https ca-certificates \
            wget software-properties-common &&\
          \
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&\
          apt-add-repository \"deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\" &&\
          \
          apt-get update &&\
          apt-get install -y \
            clang-12 lld-12 \
            libgcc-5-dev lib32gcc-5-dev \
            libgcc-5-dev-arm64-cross libgcc-5-dev-armel-cross libgcc-5-dev-armhf-cross \
            libc6-dev libc6-dev-i386 \
            libc6-dev-arm64-cross libc6-dev-armel-cross libc6-dev-armhf-cross \
          ")"
      - name: Cross-compile test C source code
        run: |
          cd ..
          sudo mv crossing /chroot-root
          sudo mkdir crossing
          cd crossing

          sudo chroot /chroot-root /bin/bash -c "$(printf "\
          cd crossing &&\
          \
          clang-12 crossing.c -o crossing-x86_64 -fuse-ld=lld -target x86_64-linux-gnu &&\
          clang-12 crossing.c -o crossing-i386 -fuse-ld=lld -target i386-linux-gnu &&\
          clang-12 crossing.c -o crossing-aarch64 -fuse-ld=lld -target aarch64-linux-gnu &&\
          clang-12 crossing.c -o crossing-armv7el -fuse-ld=lld -target armv7-linux-gnueabi &&\
          clang-12 crossing.c -o crossing-armv7hf -fuse-ld=lld -target armv7-linux-gnueabihf \
          ")"

          sudo mv /chroot-root/crossing/crossing-{x86_64,i386,aarch64,armv7} .
          sudo rm -rf /chroot-root/crossing
      - name: Upload cross-compiled C program
        uses: actions/upload-artifact@v3
        with:
          name: crossing
          path: |
            crossing-x86_64
            crossing-i386
            crossing-aarch64
            crossing-armv7
